import HeaderComponent from "@/components/HeaderComponent";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
	title: "Resume",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div
			className={`w-full h-full min-h-75`}
		>
			{children}
		</div>
	);
}
