import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProvidersLayout from "@/layouts/ProvidersLayout";
import PersonalInformationComponent from "@/components/PersonalInfoComponent";
import NavBarComponent from "@/components/NavBarComponent";
import ThemeController from "@/components/ThemeController";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`bg-base-300 transition-all duration-300`}>
				<ProvidersLayout>
					<div className="w-full h-full overflow-x-hidden overflow-y-auto py-10">
						<ThemeController />
						<section
							className={`container h-full grid grid-cols-12 gap-5 max-lg:gap-5 max-lg:grid-flow-row max-lg:place-items-center max-lg:place-content-start max-sm:px-5`}
						>
							<PersonalInformationComponent />
							<div
								className={`col-span-8 max-lg:col-span-full max-lg:w-full max-xl:col-span-7 gap-5`}
							>
								{children}
							</div>
							<NavBarComponent />
						</section>
					</div>
				</ProvidersLayout>
			</body>
		</html>
	);
}
